  # Site settings
title: "LucyLa"
email: "hieup3503@gmail.com"
description: >- # Hiển thị trong Google search & feed
baseurl: "/myblog" # repo name nếu deploy ở username.github.io/myblog
url: "https://benkei-19.github.io" # thay bằng domain hoặc GitHub Pages URL của bạn


twitter_username: ""
github_username: "benkei-19"

# Build settings
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag 

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: kramdown
  math_engine: null
  math_engine_opts:
    preview: false
show_excerpts: false 
future: true
