# Site settings
title: "My Blog"
email: "your-email@example.com"
description: >- # Hiển thị trong Google search & feed
  Đây là blog của tôi viết về machine learning và code.
baseurl: "/myblog" # repo name nếu deploy ở username.github.io/myblog
url: "https://benkei-19.github.io" # thay bằng domain hoặc GitHub Pages URL của bạn


twitter_username: ""
github_username: "benkei-19"

# Build settings
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag 

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

# Optional settings
show_excerpts: true 
