server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html index.htm;

    # Nén Gzip tối ưu tốc độ tải trang và font/css
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript image/svg+xml;

    location / {
        try_files $uri $uri/ $uri.html /404.html =404;
    }

    # Hỗ trợ tự động chuyển hướng nếu người dùng truy cập dạng /myblog/...
    location /myblog {
        rewrite ^/myblog(/.*)$ $1 last;
        rewrite ^/myblog$ / last;
    }

    # Trang 404 tùy chỉnh của blog
    error_page 404 /404.html;
    location = /404.html {
        internal;
    }
}
